// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYNy8uUHsRqToq4UdbOaM-pgKKM_XEgSQ',
    appId: '1:361335929418:web:9045fb0f6c136dcbd944b3',
    messagingSenderId: '361335929418',
    projectId: 'leaflife-bf53c',
    authDomain: 'leaflife-bf53c.firebaseapp.com',
    storageBucket: 'leaflife-bf53c.firebasestorage.app',
    measurementId: 'G-SJGX4DECBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgbfb2FUBap-alWk6UkQV8tC3ym5G9NZA',
    appId: '1:361335929418:android:36016ec9d078349ed944b3',
    messagingSenderId: '361335929418',
    projectId: 'leaflife-bf53c',
    storageBucket: 'leaflife-bf53c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf4wbHv71XJrn5tKzPKpJzJlZxm5l4Ojw',
    appId: '1:361335929418:ios:681c0bff2fdb8b58d944b3',
    messagingSenderId: '361335929418',
    projectId: 'leaflife-bf53c',
    storageBucket: 'leaflife-bf53c.firebasestorage.app',
    iosBundleId: 'com.example.leafline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf4wbHv71XJrn5tKzPKpJzJlZxm5l4Ojw',
    appId: '1:361335929418:ios:681c0bff2fdb8b58d944b3',
    messagingSenderId: '361335929418',
    projectId: 'leaflife-bf53c',
    storageBucket: 'leaflife-bf53c.firebasestorage.app',
    iosBundleId: 'com.example.leafline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYNy8uUHsRqToq4UdbOaM-pgKKM_XEgSQ',
    appId: '1:361335929418:web:518dbd799fa6aa03d944b3',
    messagingSenderId: '361335929418',
    projectId: 'leaflife-bf53c',
    authDomain: 'leaflife-bf53c.firebaseapp.com',
    storageBucket: 'leaflife-bf53c.firebasestorage.app',
    measurementId: 'G-NBZTRKFX7T',

  );
}
