// File generated by flutterfire_cli.
// This file should be added to version control.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlU9m5dmbvRhCAgMCzLxhtUwFCEZi97pU',
    appId: '1:529710790527:web:leaflineweb',
    messagingSenderId: '529710790527',
    projectId: 'leafline-dea88',
    authDomain: 'leafline-dea88.firebaseapp.com',
    databaseURL: 'https://leafline-dea88-default-rtdb.firebaseio.com',
    storageBucket: 'leafline-dea88.firebasestorage.app',
    measurementId: 'G-LEAFLINE001',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlU9m5dmbvRhCAgMCzLxhtUwFCEZi97pU',
    appId: '1:529710790527:android:2f731ca113905b53840c4a',
    messagingSenderId: '529710790527',
    projectId: 'leafline-dea88',
    databaseURL: 'https://leafline-dea88-default-rtdb.firebaseio.com',
    storageBucket: 'leafline-dea88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlU9m5dmbvRhCAgMCzLxhtUwFCEZi97pU',
    appId: '1:529710790527:ios:leaflineios',
    messagingSenderId: '529710790527',
    projectId: 'leafline-dea88',
    databaseURL: 'https://leafline-dea88-default-rtdb.firebaseio.com',
    storageBucket: 'leafline-dea88.firebasestorage.app',
    iosBundleId: 'com.nexus.leafline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlU9m5dmbvRhCAgMCzLxhtUwFCEZi97pU',
    appId: '1:529710790527:macos:leaflinemacos',
    messagingSenderId: '529710790527',
    projectId: 'leafline-dea88',
    databaseURL: 'https://leafline-dea88-default-rtdb.firebaseio.com',
    storageBucket: 'leafline-dea88.firebasestorage.app',
    iosBundleId: 'com.nexus.leafline',
  );
}
